# Usa una imagen oficial de Node.js como base
FROM node:18-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install --production

# Copia el resto del código de la aplicación al contenedor
COPY . .

# Exponer el puerto que tu aplicación utilizará
EXPOSE 3000

# Comando para iniciar tu aplicación
CMD ["node", "server.js"]
